dist: trusty
language: node_js
branches:
    only:
        - master
node_js:
    - '4'
before_script:
    - npm install -g grunt-cli@1.0.0
    - export REV=`git log --pretty=%h -1 assets`
env:
    global:
        - CXX=g++-4.8
        - PATH="node_modules/.bin:$PATH"
script:
    - "grunt test"
    - "grunt build --forecast $FORECAST --revision $REV && ./deploy.sh"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get -y install gpsbabel graphicsmagick g++-4.8
    - openssl aes-256-cbc -K $encrypted_6174b5762871_key -iv $encrypted_6174b5762871_iv
      -in ssh/id_dsa.enc -out ssh/id_dsa -d
    - chmod 600 ssh/id_dsa
