<ul class="share">
    <li class="share-item"><a href="http://twitter.com/intent/tweet/?url={{ url|ext_url|url_encode }}&amp;text={{ name|url_encode }}&amp;via={{ config.twitter|url_encode }}" class="icon-twitter share-button" title="Partager sur Twitter"><span class="share-text">Twitter</span></a></li>
    <li class="share-item"><a href="https://www.facebook.com/sharer.php?u={{ url|ext_url|url_encode }}&amp;t={{ name|url_encode }}" class="icon-facebook share-button" title="Partager sur Facebook"><span class="share-text">Facebook</span></a></li>
    <li class="share-item"><a href="https://plus.google.com/share?url={{ url|ext_url|url_encode }}" class="icon-gplus share-button" title="Partager sur Google+"><span class="share-text">Google+</a></a></li>
</ul>
