<ul class="share">
    <li class="share-item"><a href="http://twitter.com/intent/tweet/?url={{ url|ext_url|url_encode }}&text={{ name|url_encode }}&via={{ config.twitter|url_encode }}" class="icon-twitter pure-button share-button">Twitter</a></li>
    <li class="share-item"><a href="https://plus.google.com/share?url={{ url|ext_url|url_encode }}" class="icon-gplus pure-button share-button">Google+</a></li>
</ul>
